### ISSUE TITLE
Changes on KeyFile methods

### ISSUE THREAD

**Issue by alexandrunguta** [RemarkableTools/Mx.NET.SDK#24]
Can you please make the following method as public: private static KeyFile FromFilePath(string filePath) ?
It is usefull when you want to have a keyfile based on a local file path.

Also the method Wallet.FromKeyFile() should accept a KeyFile as parameter (and a password), not only the local path. Can you update it too?
Thanks!

**Comment by axenteoctavian** [comment]
Hi @alexandru96!
What are you going to do with a KeyFile object if it would be public?

It's simpler to just use a path and the password and don't use a KeyFile object..

**Comment by alexandrunguta** [comment]
No need anymore. Thanks!
